version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day at 11:30am
      interval: "daily"
      time: "11:30"

  - package-ecosystem: "pip"
    directory: "/opt"
    # Check the npm registry for updates every day at 11:30am
    schedule:
      interval: "daily"
      time: "11:30"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week at 11:30am
    schedule:
      interval: "weekly"
      time: "11:30"
