#!/usr/bin/with-contenv bash
# shellcheck shell=bash

CFG="/config/configFile.cfg"

# Downloads and copies a new configfile template if one is not present in the config dir.
if [[ ! -f "$CFG" ]]; then
    echo "No config file, providing sample"
    wget -O "$CFG" https://gitlab.com/packt-cli/packt-cli/-/raw/master/configFileTemplate.cfg
fi

# If environment arguments have been provided, switch the values in the config to these.
if [[ -n "$PACKT_EMAIL" ]]; then
    echo "ENV PACKT_EMAIL provided"
    sed -i "s/email=.*/email=$PACKT_EMAIL/" "$CFG"
else
    echo "ENV PACKT_EMAIL not set"
fi

if [[ -n "$PACKT_PASSWORD" ]]; then
    echo "ENV PACKT_PASSWORD provided"
    sed -i "s/password=.*/password=$PACKT_PASSWORD/" "$CFG"
else
    echo "ENV PACKT_PASSWORD not set"
fi

if [[ -n "$PACKT_DOWNLOAD_FORMATS" ]]; then
    echo "ENV PACKT_DOWNLOAD_FORMATS provided as \"$PACKT_DOWNLOAD_FORMATS\""
    sed -i "s/download_formats:.*/download_formats:\ $PACKT_DOWNLOAD_FORMATS/" "$CFG"
else
    echo "ENV PACKT_DOWNLOAD_FORMATS not set"
fi

if [[ -n "$PACKT_ANTICAPTCHA_KEY" ]]; then
    echo "ENV PACKT_ANTICAPTCHA_Key provided"
    sed -i "s/key:.*/key:\ $PACKT_ANTICAPTCHA_KEY/" "$CFG"
else
    echo "ENV PACKT_ANTICAPTCHA_KEY not set"
fi

if [[ -n "$PACKT_SMTP_HOST" ]]; then
    echo "ENV PACKT_SMTP_HOST provided"
    sed -i "s/host:.*/host:\ $PACKT_SMTP_HOST/" "$CFG"
else
    echo "ENV PACKT_SMTP_HOST not set"
fi

if [[ -n "$PACKT_SMTP_PORT" ]]; then
    echo "ENV PACKT_SMTP_PORT provided"
    sed -i "s/port:.*/port:\ $PACKT_SMTP_PORT/" "$CFG"
else
    echo "ENV PACKT_SMTP_PORT not set"
fi

if [[ -n "$PACKT_SMTP_PASSWORD" ]]; then
    echo "ENV PACKT_SMTP_PASSWORD provided"
    sed -i "s/password:.*/password:\ $PACKT_SMTP_PASSWORD/" "$CFG"
else
    echo "ENV PACKT_SMTP_PASSWORD not set"
fi

if [[ -n "$PACKT_SMTP_EMAIL" ]]; then
    echo "ENV PACKT_SMTP_EMAIL provided"
    sed -i "s/email:.*/email:\ $PACKT_SMTP_EMAIL/" "$CFG"
else
    echo "ENV PACKT_SMTP_EMAIL not set"
fi

if [[ -n "$PACKT_SMTP_TO_EMAILS" ]]; then
    echo "ENV PACKT_SMTP_TO_EMAILS provided"
    sed -i "s/to_emails:.*/to_emails:\ $PACKT_SMTP_TO_EMAILS/" "$CFG"
else
    echo "ENV PACKT_SMTP_TO_EMAILS not set"
fi

if [[ -n "$PACKT_SMTP_KINDLE_EMAILS" ]]; then
    echo "ENV PACKT_SMTP_KINDLE_EMAILS provided"
    sed -i "s/kindle_emails:.*/kindle_emails:\ $PACKT_SMTP_KINDLE_EMAILS/" "$CFG"
else
    echo "ENV PACKT_SMTP_KINDLE_EMAILS not set"
fi

echo "Replacing path with /data"
sed -i "s@download_folder_path:.*@download_folder_path:\ \\/data@" "$CFG"

# set permissions
lsiown -R abc:abc /config
