# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

DISABLE:
  - COPYPASTE
  - SPELL

SHOW_ELAPSED_TIME: true
IGNORE_GENERATED_FILES: true
PRINT_ALL_FILES: false
FORMATTERS_DISABLE_ERRORS: false
ERROR_ON_MISSING_EXEC_BIT: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
REPOSITORY_TRUFFLEHOG_ARGUMENTS: --exclude-paths=.git/config
DOCKERFILE_HADOLINT_CONFIG_FILE: .hadolint.yml
