# Configuration file for yamllint.
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html
---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 160
  truthy:
    # uses the key 'off' without quotes which fails the truthy check
    ignore: |
      deploy-docker-image.yml
      greetings.yml
      lint-pr-title.yml
      mega-linter.yml
