# Configuration file for yamllint.
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html
---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 150
