#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PLUGIN_REQUIREMENTS=$(find /config/plugins -maxdepth 2 -name 'requirements.txt')
if [[ -n "${PLUGIN_REQUIREMENTS}" ]]; then
    apk add --no-cache \
        build-base \
        cargo \
        libffi-dev \
        openssl-dev \
        python3-dev
    while IFS= read -r line; do
        pip3 install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine-3.17/ -r \
            "${line}"
    done <<<"${PLUGIN_REQUIREMENTS}"
    apk del --purge \
        build-dependencies
    rm -rf \
        /tmp/* \
        "${HOME}"/.cache \
        "${HOME}"/.cargo
fi
